### PR TITLE
add luajit

### PR DESCRIPTION
**Pull request by PatriceJiang**
- upgrade to luajit 2.1.0-beta3

### CODE REVIEW

**Comment by crazyhappygame** [comment]
I Think as first step Android Travis build should be fixed

**Comment by crazyhappygame** [comment]
I think that other libraries should be updated as well.

**Comment by PatriceJiang** [comment]
Currently, we will try to match the version currently in use.

**Comment by crazyhappygame** [comment]
Update to version used in cocos2d-x make sense. But please fix CI. All builds Android, iOS, mac, win32 were green. I think fix CI it should be first step.

**Pull request merged**
